use anyhow::Result;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::config::{sanitize_name, NormalizedAgent, NormalizedSkill};
use crate::frontmatter;

/// Parse a frontmatter tool list that may be a scalar string (space- or
/// comma-separated) or a YAML sequence. Shared by the per-tool skill/agent readers.
pub(crate) fn parse_frontmatter_tool_list(value: Option<&serde_yaml_ng::Value>) -> Vec<String> {
    match value {
        Some(serde_yaml_ng::Value::String(s)) => s
            .split_whitespace()
            .flat_map(|t| t.split(','))
            .map(|t| t.trim().to_string())
            .filter(|t| !t.is_empty())
            .collect(),
        Some(serde_yaml_ng::Value::Sequence(seq)) => seq
            .iter()
            .filter_map(|v| v.as_str().map(|s| s.trim().to_string()))
            .filter(|s| !s.is_empty())
            .collect(),
        _ => Vec::new(),
    }
}

/// Read `<dir>/<name>/SKILL.md` skill files into `NormalizedSkill`s.
/// Mirrors the SKILL.md folder layout every per-rule adapter writes, so `read()`
/// can round-trip the skills that `generate()` produced.
pub(crate) fn read_skills_from_dir(skills_dir: &Path) -> Result<Vec<NormalizedSkill>> {
    let mut skills = Vec::new();
    if !skills_dir.is_dir() {
        return Ok(skills);
    }
    let mut entries: Vec<_> = std::fs::read_dir(skills_dir)?
        .filter_map(|e| e.ok())
        .collect();
    entries.sort_by_key(|e| e.file_name());
    for entry in entries {
        let skill_dir = entry.path();
        if !skill_dir.is_dir() {
            continue;
        }
        let skill_file = skill_dir.join("SKILL.md");
        if !skill_file.exists() {
            continue;
        }
        let content = std::fs::read_to_string(&skill_file)?;
        let (fields, body) = frontmatter::parse(&content)?;
        let name = fields
            .get("name")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string())
            .unwrap_or_else(|| {
                skill_dir
                    .file_name()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .to_string()
            });
        let description = fields
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let allowed_tools = parse_frontmatter_tool_list(fields.get("allowed-tools"));
        skills.push(NormalizedSkill {
            name,
            description,
            content: body.trim().to_string(),
            allowed_tools,
            manual_invocation: read_manual_invocation(&fields, &skill_dir)?,
            files: read_bundled_files(&skill_dir)?,
        });
    }
    Ok(skills)
}

/// The marker conforme writes in every skill folder it generates. A folder
/// holding it is conforme's copy: once its skill leaves the source, sync
/// deletes it. A skill folder without it (written by hand in that tool) is
/// never deleted.
pub const SKILL_MARKER: &str = ".conforme";

const SKILL_MARKER_CONTENT: &str =
    "This skill folder is a copy generated by conforme from the source config.\n\
Edit the skill in the source; conforme deletes this copy when the skill leaves the source.\n";

/// Files in a skill folder that are not part of the skill's content:
/// conforme's marker and Codex policy sidecar, and system or editor litter.
fn is_skill_metadata_file(rel: &str) -> bool {
    let name = rel.rsplit('/').next().unwrap_or(rel);
    rel == "agents/openai.yaml"
        || rel == SKILL_MARKER
        || name == ".DS_Store"
        || name.ends_with('~')
        || name.ends_with(".swp")
}

/// The files bundled in a skill folder besides `SKILL.md` (scripts,
/// references, templates), by `/`-separated relative path. A sub-folder that
/// holds its own `SKILL.md` is a nested skill, not part of this one. A file
/// that is not UTF-8 text is not carried (see [`uncarried_skill_files`]).
pub(crate) fn read_bundled_files(skill_dir: &Path) -> Result<BTreeMap<String, String>> {
    let mut files = BTreeMap::new();
    for path in skill_bundle_paths(skill_dir)? {
        if let Ok(content) = std::fs::read_to_string(&path) {
            files.insert(bundle_rel(skill_dir, &path), content);
        }
    }
    Ok(files)
}

/// Bundled files of a skill folder that conforme cannot carry to the other
/// tools (not UTF-8 text: images, binaries).
pub fn uncarried_skill_files(skill_dir: &Path) -> Result<Vec<PathBuf>> {
    Ok(skill_bundle_paths(skill_dir)?
        .into_iter()
        .filter(|path| std::fs::read_to_string(path).is_err())
        .collect())
}

fn bundle_rel(skill_dir: &Path, path: &Path) -> String {
    path.strip_prefix(skill_dir)
        .unwrap_or(path)
        .components()
        .map(|c| c.as_os_str().to_string_lossy().to_string())
        .collect::<Vec<_>>()
        .join("/")
}

fn skill_bundle_paths(skill_dir: &Path) -> Result<Vec<PathBuf>> {
    let mut found = Vec::new();
    let mut stack = vec![skill_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir)?.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.is_dir() {
                if !path.join("SKILL.md").exists() {
                    stack.push(path);
                }
            } else if path.is_file() {
                let rel = bundle_rel(skill_dir, &path);
                if rel != "SKILL.md" && !is_skill_metadata_file(&rel) {
                    found.push(path);
                }
            }
        }
    }
    found.sort();
    Ok(found)
}

/// Bundled files left in a skill folder whose `SKILL.md` conforme generates
/// but that the source no longer bundles: the copy must mirror the source.
pub(crate) fn stale_bundled_files(
    skill_dir: &Path,
    expected: &std::collections::HashSet<PathBuf>,
) -> Result<Vec<PathBuf>> {
    if !expected.contains(&skill_dir.join("SKILL.md")) {
        return Ok(Vec::new());
    }
    Ok(skill_bundle_paths(skill_dir)?
        .into_iter()
        .filter(|path| !expected.contains(path))
        .collect())
}

/// Every file of a skill folder conforme generated but whose skill is no
/// longer expected: the folder holds conforme's marker, and its `SKILL.md`
/// is not in `expected`. A folder without the marker is someone's own skill.
pub(crate) fn stale_skill_folder_files(
    skill_dir: &Path,
    expected: &std::collections::HashSet<PathBuf>,
) -> Result<Vec<PathBuf>> {
    if !skill_dir.join(SKILL_MARKER).is_file() || expected.contains(&skill_dir.join("SKILL.md")) {
        return Ok(Vec::new());
    }
    let mut files = Vec::new();
    let mut stack = vec![skill_dir.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for path in std::fs::read_dir(&dir)?
            .filter_map(|e| e.ok())
            .map(|e| e.path())
        {
            if path.is_dir() {
                // A nested skill inside the copy is not conforme's.
                if !path.join("SKILL.md").exists() {
                    stack.push(path);
                }
            } else {
                files.push(path);
            }
        }
    }
    files.sort();
    Ok(files)
}

/// The bundled files of `skill` written into a tool's `skill_dir`, and
/// conforme's marker.
fn bundled_outputs(skill_dir: &Path, skill: &NormalizedSkill) -> Vec<(PathBuf, String)> {
    skill
        .files
        .iter()
        .map(|(rel, content)| (skill_dir.join(rel), content.clone()))
        .chain(std::iter::once((
            skill_dir.join(SKILL_MARKER),
            SKILL_MARKER_CONTENT.to_string(),
        )))
        .collect()
}

/// Depth used for tools that walk their skills root without a limit.
pub(crate) const UNBOUNDED_SKILL_DEPTH: usize = 16;

/// Read skills from every `SKILL.md` folder under `skills_dir`, up to
/// `max_depth` levels below it, for the tools that search their skills root
/// recursively (Codex: 6 levels, Amp: 5, Cursor and OpenCode: unbounded). A
/// folder holding a `SKILL.md` is one skill; its sub-folders are not
/// searched. A skill nested deeper than one level is written back flat.
pub(crate) fn read_skills_recursive(
    skills_dir: &Path,
    max_depth: usize,
) -> Result<Vec<NormalizedSkill>> {
    let mut skills = read_skills_from_dir(skills_dir)?;
    let mut frontier: Vec<PathBuf> = Vec::new();
    if skills_dir.is_dir() {
        frontier.push(skills_dir.to_path_buf());
    }
    for _ in 1..max_depth {
        let mut next = Vec::new();
        for dir in frontier {
            let mut children: Vec<PathBuf> = std::fs::read_dir(&dir)?
                .filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| p.is_dir() && !p.join("SKILL.md").exists())
                .collect();
            children.sort();
            for child in children {
                for skill in read_skills_from_dir(&child)? {
                    if !skills.iter().any(|s| s.name == skill.name) {
                        skills.push(skill);
                    }
                }
                next.push(child);
            }
        }
        if next.is_empty() {
            break;
        }
        frontier = next;
    }
    Ok(skills)
}

/// Read flat `<dir>/<name>.md` skill files, the single-file layout the
/// DeepSeek Harness accepts next to `<name>/SKILL.md` bundles.
pub(crate) fn read_flat_skills_from_dir(skills_dir: &Path) -> Result<Vec<NormalizedSkill>> {
    let mut skills = Vec::new();
    if !skills_dir.is_dir() {
        return Ok(skills);
    }
    let mut paths: Vec<PathBuf> = std::fs::read_dir(skills_dir)?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_file() && p.extension().is_some_and(|e| e == "md"))
        .collect();
    paths.sort();
    for path in paths {
        let content = std::fs::read_to_string(&path)?;
        let Ok((fields, body)) = frontmatter::parse(&content) else {
            continue;
        };
        // A flat file is a skill only with a kebab-case `name` and a
        // `description` (a README beside the skills is not one).
        let text = |key: &str| {
            fields
                .get(key)
                .and_then(|v| v.as_str())
                .map(str::trim)
                .filter(|s| !s.is_empty())
        };
        let (Some(name), Some(description)) = (text("name"), text("description")) else {
            continue;
        };
        if sanitize_name(name) != name {
            continue;
        }
        skills.push(NormalizedSkill {
            name: name.to_string(),
            description: description.to_string(),
            content: body.trim().to_string(),
            allowed_tools: parse_frontmatter_tool_list(fields.get("allowed-tools")),
            manual_invocation: fields
                .get("disable-model-invocation")
                .and_then(yaml_flag)
                .unwrap_or(false),
            files: Default::default(),
        });
    }
    Ok(skills)
}

/// A frontmatter boolean. Claude Code documents that boolean fields accept
/// `yes`/`no`, `on`/`off` and `1`/`0` besides `true`/`false`; YAML 1.2
/// parses those as strings or integers, so they are matched here.
pub(crate) fn yaml_flag(value: &serde_yaml_ng::Value) -> Option<bool> {
    match value {
        serde_yaml_ng::Value::Bool(b) => Some(*b),
        serde_yaml_ng::Value::Number(n) => match n.as_i64() {
            Some(1) => Some(true),
            Some(0) => Some(false),
            _ => None,
        },
        serde_yaml_ng::Value::String(s) => match s.trim().to_ascii_lowercase().as_str() {
            "true" | "yes" | "on" | "1" => Some(true),
            "false" | "no" | "off" | "0" => Some(false),
            _ => None,
        },
        _ => None,
    }
}

/// Read explicit-only settings from supported skill metadata.
pub(crate) fn read_manual_invocation(
    fields: &BTreeMap<String, serde_yaml_ng::Value>,
    skill_dir: &Path,
) -> Result<bool> {
    if fields.get("disable-model-invocation").and_then(yaml_flag) == Some(true) {
        return Ok(true);
    }
    // Devin: `triggers` lists who may invoke the skill (`user`, `model`).
    if let Some(serde_yaml_ng::Value::Sequence(triggers)) = fields.get("triggers") {
        return Ok(!triggers.iter().any(|t| t.as_str() == Some("model")));
    }
    if let Some(value) = fields
        .get("metadata")
        .and_then(|v| v.get("opencode/autoinvoke"))
    {
        if value.as_bool() == Some(false) || value.as_str() == Some("false") {
            return Ok(true);
        }
    }
    let policy_path = skill_dir.join("agents/openai.yaml");
    if policy_path.exists() {
        let value: serde_yaml_ng::Value =
            serde_yaml_ng::from_str(&std::fs::read_to_string(policy_path)?)?;
        return Ok(value
            .get("policy")
            .and_then(|v| v.get("allow_implicit_invocation"))
            .and_then(|v| v.as_bool())
            == Some(false));
    }
    Ok(false)
}

/// The `description` to write for a skill or agent. Codex, Copilot, Gemini,
/// OpenCode and Zoo Code silently skip a skill or agent without one (Gemini
/// also rejects an empty string), so an empty description falls back to the
/// name rather than being left out.
pub(crate) fn description_or_name(description: &str, name: &str) -> String {
    if description.trim().is_empty() {
        name.to_string()
    } else {
        description.to_string()
    }
}

fn add_invocation_fields(
    fields: &mut BTreeMap<String, serde_yaml_ng::Value>,
    skill: &NormalizedSkill,
) {
    if !skill.manual_invocation {
        return;
    }
    fields.insert(
        "disable-model-invocation".into(),
        serde_yaml_ng::Value::Bool(true),
    );
    let mut metadata = serde_yaml_ng::Mapping::new();
    metadata.insert("opencode/autoinvoke".into(), "false".into());
    fields.insert("metadata".into(), serde_yaml_ng::Value::Mapping(metadata));
}

/// The Codex `agents/openai.yaml` policy sidecar of a skill. Only Codex reads
/// it, so it is created (`create`) only in `.agents/skills/`, the root Codex
/// scans; elsewhere an existing sidecar is kept in step with the skill but
/// never added, since no tool there would consume it.
fn invocation_policy(
    skill_dir: &Path,
    skill: &NormalizedSkill,
    create: bool,
) -> Result<Option<(PathBuf, String)>> {
    let path = skill_dir.join("agents/openai.yaml");
    if !path.exists() && !(create && skill.manual_invocation) {
        return Ok(None);
    }
    let mut fields: BTreeMap<String, serde_yaml_ng::Value> = if path.exists() {
        serde_yaml_ng::from_str(&std::fs::read_to_string(&path)?)?
    } else {
        BTreeMap::new()
    };
    let policy = fields
        .entry("policy".into())
        .or_insert_with(|| serde_yaml_ng::Value::Mapping(Default::default()));
    let policy = policy.as_mapping_mut().ok_or_else(|| {
        anyhow::anyhow!("skill policy must be a YAML mapping: {}", path.display())
    })?;
    policy.insert(
        "allow_implicit_invocation".into(),
        serde_yaml_ng::Value::Bool(!skill.manual_invocation),
    );
    Ok(Some((path, serde_yaml_ng::to_string(&fields)?)))
}

/// Read `<dir>/*.md` agent files into `NormalizedAgent`s (the common frontmatter
/// subset: `name`, `description`, `model`, `tools`). Used by adapters whose
/// subagents live one-per-markdown-file. `recursive` follows sub-directories,
/// for tools that scan their agents directory recursively (OpenCode).
pub(crate) fn read_agents_from_dir(
    agents_dir: &Path,
    recursive: bool,
) -> Result<Vec<NormalizedAgent>> {
    read_agent_files(&agent_files(agents_dir, recursive)?)
}

/// The `*.md` files of an agents directory, sorted (see [`read_agents_from_dir`]).
pub(crate) fn agent_files(agents_dir: &Path, recursive: bool) -> Result<Vec<PathBuf>> {
    if !agents_dir.is_dir() {
        return Ok(Vec::new());
    }
    if recursive {
        return crate::adapters::collect_rule_files(agents_dir, "md");
    }
    let mut paths: Vec<PathBuf> = std::fs::read_dir(agents_dir)?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_file() && p.extension().is_some_and(|e| e == "md"))
        .collect();
    paths.sort();
    Ok(paths)
}

/// Read agent markdown files (see [`read_agents_from_dir`]).
pub(crate) fn read_agent_files(paths: &[PathBuf]) -> Result<Vec<NormalizedAgent>> {
    let mut agents = Vec::new();
    for path in paths {
        let content = std::fs::read_to_string(path)?;
        let (fields, body) = frontmatter::parse(&content)?;
        let name = fields
            .get("name")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string())
            .unwrap_or_else(|| agent_name_from_path(path));
        let description = fields
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let model = fields
            .get("model")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string());
        let tools = parse_frontmatter_tool_list(fields.get("tools"));
        agents.push(NormalizedAgent {
            name,
            description,
            content: body.trim().to_string(),
            model,
            tools,
            ..Default::default()
        });
    }
    Ok(agents)
}

/// The agent name a file stands for when its frontmatter has no `name`:
/// the file name without `.agent.md` (Copilot) or `.md`.
fn agent_name_from_path(path: &Path) -> String {
    let file_name = path.file_name().unwrap_or_default().to_string_lossy();
    file_name
        .strip_suffix(".agent.md")
        .or_else(|| file_name.strip_suffix(".md"))
        .unwrap_or(&file_name)
        .to_string()
}

/// Generate Claude Code skill files in `.claude/skills/<name>/SKILL.md`.
pub fn generate_claude_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".claude").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );
        if !skill.allowed_tools.is_empty() {
            fields.insert(
                "allowed-tools".to_string(),
                serde_yaml_ng::Value::String(skill.allowed_tools.join(" ")),
            );
        }

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate Mistral Vibe skill files in `.vibe/skills/<name>/SKILL.md`. Vibe
/// requires a kebab-case `name` and a `description`, and keeps a skill out of
/// automatic use with `disable-model-invocation: true`.
pub fn generate_vibe_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".vibe").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
    }

    Ok(files)
}

/// Mistral Vibe's built-in tools, by the Gemini CLI name `gemini_tools`
/// translates to first: custom subagents get built-in tools only.
const VIBE_TOOLS: &[(&str, &str)] = &[
    ("read_file", "read_file"),
    ("read_many_files", "read_file"),
    ("list_directory", "read_file"),
    ("glob", "grep"),
    ("grep_search", "grep"),
    ("search_file_content", "grep"),
    ("write_file", "write_file"),
    ("replace", "edit"),
    ("run_shell_command", "bash"),
    ("web_fetch", "web_fetch"),
    ("google_web_search", "web_search"),
    ("write_todos", "todo"),
    ("invoke_agent", "task"),
    ("activate_skill", "skill"),
    ("ask_user", "ask_user_question"),
];

/// Translate a tool list into Vibe's built-in tool names; a restricted list
/// in which nothing translates becomes read-only access, never every tool.
fn vibe_tools(tools: &[String]) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for gemini in gemini_tools(tools) {
        if let Some((_, vibe)) = VIBE_TOOLS.iter().find(|(g, _)| *g == gemini) {
            if !out.iter().any(|t| t == vibe) {
                out.push(vibe.to_string());
            }
        }
    }
    if out.is_empty() && !tools.is_empty() {
        out.push("read_file".to_string());
    }
    out
}

/// Generate Mistral Vibe subagents as `.vibe/agents/<name>.toml`
/// (`agent_type = "subagent"`, a required `description`, the prompt as
/// `instructions`, tools as `enabled_tools`). `model` is left out: Vibe models
/// are aliases each user defines.
pub fn generate_vibe_agents(
    project_root: &Path,
    agents: &[NormalizedAgent],
) -> Result<Vec<(PathBuf, String)>> {
    let agents_dir = project_root.join(".vibe").join("agents");
    let mut files = Vec::new();
    for agent in agents {
        let mut document = toml_edit::DocumentMut::new();
        document["agent_type"] = toml_edit::value("subagent");
        document["description"] =
            toml_edit::value(description_or_name(&agent.description, &agent.name));
        document["instructions"] = toml_edit::value(agent.content.trim());
        let tools = vibe_tools(&agent.tools);
        if !tools.is_empty() {
            let mut array = toml_edit::Array::new();
            for tool in tools {
                array.push(tool);
            }
            document["enabled_tools"] = toml_edit::value(array);
        }
        files.push((
            agents_dir.join(format!("{}.toml", sanitize_name(&agent.name))),
            document.to_string(),
        ));
    }
    Ok(files)
}

/// Whether a `.vibe/agents/*.toml` file is a subagent (`agent_type =
/// "subagent"`), the kind conforme writes; anything else is a mode the user
/// defined.
pub(crate) fn is_vibe_subagent_file(path: &Path) -> bool {
    std::fs::read_to_string(path)
        .ok()
        .and_then(|content| content.parse::<toml::Value>().ok())
        .is_some_and(|value| {
            value.get("agent_type").and_then(toml::Value::as_str) == Some("subagent")
        })
}

/// Read Mistral Vibe subagents back from `.vibe/agents/*.toml`. The prompt is
/// `instructions`, or the `.vibe/prompts/<system_prompt_id>.md` file.
pub(crate) fn read_vibe_agents(project_root: &Path) -> Result<Vec<NormalizedAgent>> {
    let agents_dir = project_root.join(".vibe").join("agents");
    let mut agents = Vec::new();
    if !agents_dir.is_dir() {
        return Ok(agents);
    }
    let mut paths: Vec<PathBuf> = std::fs::read_dir(&agents_dir)?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|e| e == "toml") && is_vibe_subagent_file(p))
        .collect();
    paths.sort();
    for path in paths {
        let value: toml::Value = std::fs::read_to_string(&path)?.parse()?;
        let text = |key: &str| {
            value
                .get(key)
                .and_then(toml::Value::as_str)
                .map(str::to_string)
        };
        let content = match text("instructions") {
            Some(instructions) => instructions,
            None => text("system_prompt_id")
                .and_then(|id| {
                    std::fs::read_to_string(
                        project_root
                            .join(".vibe")
                            .join("prompts")
                            .join(format!("{id}.md")),
                    )
                    .ok()
                })
                .unwrap_or_default(),
        };
        let tools = value
            .get("enabled_tools")
            .and_then(toml::Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(|v| v.as_str().map(str::to_string))
                    .collect()
            })
            .unwrap_or_default();
        agents.push(NormalizedAgent {
            name: path
                .file_stem()
                .unwrap_or_default()
                .to_string_lossy()
                .to_string(),
            description: text("description").unwrap_or_default(),
            content: content.trim().to_string(),
            tools,
            ..Default::default()
        });
    }
    Ok(agents)
}

/// Generate Cursor skill files in `.cursor/skills/<name>/SKILL.md`.
/// Cursor skills use `name` and `description` in frontmatter.
pub fn generate_cursor_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".cursor").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate Codex/OpenCode skill files in `.agents/skills/<name>/SKILL.md`.
pub fn generate_codex_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".agents").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, true)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate GitHub Copilot skill files in `.github/skills/<name>/SKILL.md`.
///
/// Copilot documents skills at `.github/skills/<skill-name>/SKILL.md` (the same
/// location for Copilot CLI and the cloud agent), with `name` and `description`
/// required and `allowed-tools` available to pre-approve tools. This supersedes
/// the older `.github/prompts/<name>.prompt.md` layout conforme used to emit —
/// prompt files are a separate VS Code feature, not Copilot's skills format.
pub fn generate_copilot_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".github").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );
        if !skill.allowed_tools.is_empty() {
            fields.insert(
                "allowed-tools".to_string(),
                serde_yaml_ng::Value::String(skill.allowed_tools.join(" ")),
            );
        }

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate Copilot agent files in `.github/agents/<name>.agent.md`.
pub fn generate_copilot_agents(
    project_root: &Path,
    agents: &[crate::config::NormalizedAgent],
) -> Result<Vec<(PathBuf, String)>> {
    let agents_dir = project_root.join(".github").join("agents");
    let mut files = Vec::new();

    for agent in agents {
        let filename = format!("{}.agent.md", sanitize_name(&agent.name));
        let mut fields = BTreeMap::new();
        fields.insert(
            "name".to_string(),
            serde_yaml_ng::Value::String(agent.name.clone()),
        );
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&agent.description, &agent.name)),
        );
        if let Some(model) = copilot_model(agent.model.as_deref()) {
            fields.insert(
                "model".to_string(),
                serde_yaml_ng::Value::String(model.to_string()),
            );
        }
        if !agent.tools.is_empty() {
            let yaml_tools: Vec<serde_yaml_ng::Value> = agent
                .tools
                .iter()
                .map(|t| serde_yaml_ng::Value::String(t.clone()))
                .collect();
            fields.insert(
                "tools".to_string(),
                serde_yaml_ng::Value::Sequence(yaml_tools),
            );
        }

        let content = frontmatter::serialize(&fields, &format!("{}\n", agent.content))?;
        files.push((agents_dir.join(filename), content));
    }

    Ok(files)
}

/// Generate Claude Code subagent files in `.claude/agents/<name>.md`.
pub fn generate_claude_agents(
    project_root: &Path,
    agents: &[crate::config::NormalizedAgent],
) -> Result<Vec<(PathBuf, String)>> {
    let agents_dir = project_root.join(".claude").join("agents");
    let mut files = Vec::new();

    for agent in agents {
        let filename = format!("{}.md", sanitize_name(&agent.name));
        let mut fields = BTreeMap::new();
        fields.insert(
            "name".to_string(),
            serde_yaml_ng::Value::String(sanitize_name(&agent.name)),
        );
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&agent.description, &agent.name)),
        );
        if let Some(model) = claude_model(agent.model.as_deref()) {
            fields.insert(
                "model".to_string(),
                serde_yaml_ng::Value::String(model.to_string()),
            );
        }
        // Names from other hosts are translated; a list in which nothing
        // resolves would make Claude Code refuse to launch the subagent, so an
        // untranslatable list becomes read-only access (never every tool).
        let tools = claude_tools(&agent.tools);
        if !tools.is_empty() {
            fields.insert(
                "tools".to_string(),
                serde_yaml_ng::Value::String(tools.join(", ")),
            );
        }
        if let Some(color) = &agent.color {
            fields.insert(
                "color".to_string(),
                serde_yaml_ng::Value::String(color.clone()),
            );
        }
        if let Some(permission_mode) = &agent.permission_mode {
            fields.insert(
                "permissionMode".to_string(),
                serde_yaml_ng::Value::String(permission_mode.clone()),
            );
        }

        let content = frontmatter::serialize(&fields, &format!("{}\n", agent.content))?;
        files.push((agents_dir.join(filename), content));
    }

    Ok(files)
}

/// Generate Cursor agent files in `.cursor/agents/<name>.md`.
/// Cursor subagents use `.md` (not `.mdc`) and support only `name`, `description`,
/// `model`, `readonly`, `is_background`. The `tools` field is not recognized;
/// tool access is inherited from the parent agent.
pub fn generate_cursor_agents(
    project_root: &Path,
    agents: &[NormalizedAgent],
) -> Result<Vec<(PathBuf, String)>> {
    let agents_dir = project_root.join(".cursor").join("agents");
    let mut files = Vec::new();

    for agent in agents {
        let filename = format!("{}.md", sanitize_name(&agent.name));
        let mut fields = BTreeMap::new();
        // Cursor subagent names use lowercase letters and hyphens.
        fields.insert(
            "name".to_string(),
            serde_yaml_ng::Value::String(sanitize_name(&agent.name)),
        );
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&agent.description, &agent.name)),
        );
        if let Some(model) = cursor_model(agent.model.as_deref()) {
            fields.insert(
                "model".to_string(),
                serde_yaml_ng::Value::String(model.to_string()),
            );
        }

        let content = frontmatter::serialize(&fields, &format!("{}\n", agent.content))?;
        files.push((agents_dir.join(filename), content));
    }

    Ok(files)
}

/// Generate Kiro agent files in `.kiro/agents/<name>.md`.
pub fn generate_kiro_agents(
    project_root: &Path,
    agents: &[NormalizedAgent],
) -> Result<Vec<(PathBuf, String)>> {
    let agents_dir = project_root.join(".kiro").join("agents");
    let mut files = Vec::new();

    for agent in agents {
        let filename = format!("{}.md", sanitize_name(&agent.name));
        // Kiro derives the agent name from the file path — the custom-agent
        // frontmatter has no `name` field, so we do not emit one.
        let mut fields = BTreeMap::new();
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&agent.description, &agent.name)),
        );
        if let Some(model) = kiro_model(agent.model.as_deref()) {
            fields.insert(
                "model".to_string(),
                serde_yaml_ng::Value::String(model.to_string()),
            );
        }
        insert_tool_list(&mut fields, &kiro_tools(&agent.tools));

        let content = frontmatter::serialize(&fields, &format!("{}\n", agent.content))?;
        files.push((agents_dir.join(filename), content));
    }

    Ok(files)
}

/// Common tool names across hosts (Claude Code, Copilot, Gemini CLI, Kiro,
/// Codex) and their equivalent in each tool that validates `tools` against
/// its own vocabulary. Matching is case-insensitive.
const TOOL_EQUIVALENTS: &[(&str, &str, &str, &str)] = &[
    // (source name, Gemini tool, Kiro tool, Claude Code tool)
    ("read", "read_file", "read", "Read"),
    ("read_file", "read_file", "read", "Read"),
    ("read_many_files", "read_many_files", "read", "Read"),
    ("fs_read", "read_file", "read", "Read"),
    ("glob", "glob", "glob", "Glob"),
    ("grep", "grep_search", "grep", "Grep"),
    ("grep_search", "grep_search", "grep", "Grep"),
    ("search_file_content", "grep_search", "grep", "Grep"),
    ("search", "grep_search", "grep", "Grep"),
    ("codebase", "grep_search", "grep", "Grep"),
    ("ls", "list_directory", "read", "Glob"),
    ("list_directory", "list_directory", "read", "Glob"),
    ("write", "write_file", "write", "Write"),
    ("write_file", "write_file", "write", "Write"),
    ("fs_write", "write_file", "write", "Write"),
    ("edit", "replace", "write", "Edit"),
    ("replace", "replace", "write", "Edit"),
    ("multiedit", "replace", "write", "Edit"),
    ("editfiles", "replace", "write", "Edit"),
    ("notebookedit", "replace", "write", "NotebookEdit"),
    ("bash", "run_shell_command", "shell", "Bash"),
    ("run_shell_command", "run_shell_command", "shell", "Bash"),
    ("execute", "run_shell_command", "shell", "Bash"),
    ("execute_bash", "run_shell_command", "shell", "Bash"),
    ("execute_cmd", "run_shell_command", "shell", "Bash"),
    ("exec", "run_shell_command", "shell", "Bash"),
    ("shell", "run_shell_command", "shell", "Bash"),
    ("terminal", "run_shell_command", "shell", "Bash"),
    ("runcommands", "run_shell_command", "shell", "Bash"),
    ("powershell", "run_shell_command", "shell", "PowerShell"),
    ("webfetch", "web_fetch", "web_fetch", "WebFetch"),
    ("web_fetch", "web_fetch", "web_fetch", "WebFetch"),
    ("fetch", "web_fetch", "web_fetch", "WebFetch"),
    ("websearch", "google_web_search", "web_search", "WebSearch"),
    ("web_search", "google_web_search", "web_search", "WebSearch"),
    (
        "google_web_search",
        "google_web_search",
        "web_search",
        "WebSearch",
    ),
    ("web", "web_fetch", "web", "WebFetch"),
    // Kiro's `todo_list` tag only applies to engines that provide it; V3's
    // task-tracking tool is `todo`.
    ("todowrite", "write_todos", "todo", "TodoWrite"),
    ("write_todos", "write_todos", "todo", "TodoWrite"),
    ("todo", "write_todos", "todo", "TodoWrite"),
    ("todo_list", "write_todos", "todo", "TodoWrite"),
    ("task", "invoke_agent", "subagent", "Agent"),
    ("agent", "invoke_agent", "subagent", "Agent"),
    ("invoke_agent", "invoke_agent", "subagent", "Agent"),
    ("subagent", "invoke_agent", "subagent", "Agent"),
    ("use_subagent", "invoke_agent", "subagent", "Agent"),
    ("askuserquestion", "ask_user", "", "AskUserQuestion"),
    ("ask_user", "ask_user", "", "AskUserQuestion"),
    ("skill", "activate_skill", "", "Skill"),
    ("activate_skill", "activate_skill", "", "Skill"),
    ("ask_user_question", "ask_user", "", "AskUserQuestion"),
    // Every MCP tool: Gemini `mcp_*`, Kiro `@mcp`; Claude Code has no
    // wildcard for it.
    ("mcp_*", "mcp_*", "@mcp", ""),
    ("@mcp", "mcp_*", "@mcp", ""),
];

/// Gemini CLI built-in tool names (`ALL_BUILTIN_TOOL_NAMES` plus the legacy
/// `search_file_content` alias). A subagent listing any other name is
/// rejected whole.
const GEMINI_TOOLS: &[&str] = &[
    "glob",
    "write_todos",
    "write_file",
    "google_web_search",
    "web_fetch",
    "replace",
    "run_shell_command",
    "grep_search",
    "search_file_content",
    "read_many_files",
    "read_file",
    "list_directory",
    "activate_skill",
    "ask_user",
    "tracker_create_task",
    "tracker_update_task",
    "tracker_get_task",
    "tracker_list_tasks",
    "tracker_add_dependency",
    "tracker_visualize",
    "get_internal_docs",
    "enter_plan_mode",
    "exit_plan_mode",
    "update_topic",
    "complete_task",
    "invoke_agent",
    "read_mcp_resource",
    "list_mcp_resources",
    "*",
];

/// Kiro agent `tools` values: the category tags, the individual built-in
/// tools, and their documented legacy aliases (besides `@server[/tool]`).
const KIRO_TOOLS: &[&str] = &[
    // tags
    "read",
    "write",
    "shell",
    "web",
    "subagent",
    "knowledge",
    "todo_list",
    "@builtin",
    "@mcp",
    "*",
    // built-in tools
    "glob",
    "grep",
    "aws",
    "web_search",
    "web_fetch",
    "introspect",
    "code",
    "tool_search",
    "delegate",
    "report",
    "thinking",
    "todo",
    "goal",
    "session",
    // aliases
    "fs_read",
    "fsRead",
    "fs_write",
    "fsWrite",
    "execute_bash",
    "execute_cmd",
    "use_aws",
    "use_subagent",
];

/// Claude Code built-in tool names a subagent's `tools` may list. A list in
/// which nothing resolves makes Claude Code refuse to launch the subagent.
const CLAUDE_TOOLS: &[&str] = &[
    "Agent",
    "Artifact",
    "AskUserQuestion",
    "Bash",
    "CronCreate",
    "CronDelete",
    "CronList",
    "Edit",
    "EndConversation",
    "EnterPlanMode",
    "EnterWorktree",
    "ExitPlanMode",
    "ExitWorktree",
    "Glob",
    "Grep",
    "ListAgents",
    "ListMcpResourcesTool",
    "LSP",
    "Monitor",
    "NotebookEdit",
    "PowerShell",
    "PushNotification",
    "Read",
    "ReadMcpResourceTool",
    "RemoteTrigger",
    "ReportFindings",
    "ScheduleWakeup",
    "SendFeedback",
    "SendMessage",
    "SendUserFile",
    "ShareOnboardingGuide",
    "Skill",
    "SubagentHandback",
    "Task",
    "TaskCreate",
    "TaskGet",
    "TaskList",
    "TaskOutput",
    "TaskStop",
    "TaskUpdate",
    "TodoWrite",
    "ToolSearch",
    "WaitForMcpServers",
    "WebFetch",
    "WebSearch",
    "Workflow",
    "Write",
];

/// An MCP tool reference in any host's spelling, as `(server, tool)`, where
/// `tool` is `None` for "every tool of the server":
/// Claude Code / Devin `mcp__srv__tool` and `mcp__srv`, Gemini
/// `mcp_srv_tool` and `mcp_srv_*`, Kiro `@srv/tool` and `@srv`.
fn parse_mcp_tool(name: &str) -> Option<(&str, Option<&str>)> {
    if let Some(rest) = name.strip_prefix("mcp__") {
        return match rest.split_once("__") {
            Some((server, "*")) => Some((server, None)),
            Some((server, tool)) => Some((server, Some(tool))),
            None => Some((rest, None)),
        }
        .filter(|(server, _)| !server.is_empty());
    }
    if let Some(rest) = name.strip_prefix("mcp_") {
        let (server, tool) = rest.split_once('_')?;
        let tool = if tool == "*" { None } else { Some(tool) };
        return (!server.is_empty() && tool != Some("")).then_some((server, tool));
    }
    if let Some(rest) = name.strip_prefix('@') {
        if rest == "builtin" || rest == "mcp" {
            return None;
        }
        return match rest.split_once('/') {
            Some((server, tool)) => Some((server, Some(tool))),
            None => Some((rest, None)),
        }
        .filter(|(server, _)| !server.is_empty());
    }
    None
}

/// Whether `name` is an MCP tool name Gemini's agent validator accepts
/// (`mcp_<server>_<tool>` or `mcp_<server>_*`, slug characters only).
fn is_gemini_mcp_tool(name: &str) -> bool {
    let slug = |s: &str| {
        !s.is_empty()
            && s.chars()
                .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | ':' | '-'))
    };
    name.strip_prefix("mcp_")
        .filter(|rest| !rest.starts_with('_'))
        .and_then(|rest| rest.split_once('_'))
        .is_some_and(|(server, tool)| {
            slug(server) && (tool == "*" || (slug(tool) && !tool.chars().all(|c| c == '_')))
        })
}

/// Translate a tool list into Gemini CLI tool names. Names Gemini already
/// knows (built-ins, `*`, `mcp_<server>_<tool>`, `discovered_tool_*`) pass
/// through, MCP tools in another host's spelling are rewritten, known
/// equivalents are mapped, and anything else is dropped so the agent is not
/// rejected.
fn gemini_tools(tools: &[String]) -> Vec<String> {
    translate_tools(
        tools,
        |t| {
            if GEMINI_TOOLS.contains(&t)
                || is_gemini_mcp_tool(t)
                || t.starts_with("discovered_tool_")
            {
                return Some(t.to_string());
            }
            let (server, tool) = parse_mcp_tool(t)?;
            let fqn = format!("mcp_{server}_{}", tool.unwrap_or("*"));
            is_gemini_mcp_tool(&fqn).then_some(fqn)
        },
        |row| row.1,
        "read_file",
    )
}

/// Translate a tool list into Kiro tools and tags, the same way as
/// [`gemini_tools`]; MCP tools become `@server[/tool]`.
fn kiro_tools(tools: &[String]) -> Vec<String> {
    translate_tools(
        tools,
        |t| {
            if KIRO_TOOLS.contains(&t) || t.starts_with('@') {
                return Some(t.to_string());
            }
            let (server, tool) = parse_mcp_tool(t)?;
            Some(match tool {
                Some(tool) => format!("@{server}/{tool}"),
                None => format!("@{server}"),
            })
        },
        |row| row.2,
        "read",
    )
}

/// Translate a tool list into Claude Code tool names, the same way as
/// [`gemini_tools`]; MCP tools become `mcp__server[__tool]`, and
/// `Agent(type)`-style restrictions of a known tool pass through.
fn claude_tools(tools: &[String]) -> Vec<String> {
    // Kiro's `*` / `@builtin` mean every tool; Claude Code has no wildcard,
    // and an absent `tools` means the same.
    if tools.iter().any(|t| t == "*" || t == "@builtin") {
        return Vec::new();
    }
    translate_tools(
        tools,
        |t| {
            let base = t.split_once('(').map_or(t, |(base, _)| base);
            if CLAUDE_TOOLS.contains(&base) {
                return Some(t.to_string());
            }
            let (server, tool) = parse_mcp_tool(t)?;
            Some(match tool {
                Some(tool) => format!("mcp__{server}__{tool}"),
                None => format!("mcp__{server}"),
            })
        },
        |row| row.3,
        "Read",
    )
}

/// Translate `tools` into a target vocabulary. A restricted source list in
/// which nothing translates becomes `[read_only]` rather than an empty list:
/// leaving `tools` out would hand the agent every tool, including shell and
/// write access the source never granted.
fn translate_tools(
    tools: &[String],
    native: impl Fn(&str) -> Option<String>,
    target: fn(&(&str, &'static str, &'static str, &'static str)) -> &'static str,
    read_only: &str,
) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for tool in tools {
        let mapped = native(tool).or_else(|| {
            TOOL_EQUIVALENTS
                .iter()
                .find(|row| row.0.eq_ignore_ascii_case(tool))
                .map(target)
                .filter(|name| !name.is_empty())
                .map(str::to_string)
        });
        if let Some(name) = mapped {
            if !out.contains(&name) {
                out.push(name);
            }
        }
    }
    if out.is_empty() && !tools.is_empty() {
        out.push(read_only.to_string());
    }
    out
}

/// Insert `tools` as a YAML list, or leave it out when empty.
fn insert_tool_list(fields: &mut BTreeMap<String, serde_yaml_ng::Value>, tools: &[String]) {
    if tools.is_empty() {
        return;
    }
    let yaml_tools = tools
        .iter()
        .map(|t| serde_yaml_ng::Value::String(t.clone()))
        .collect();
    fields.insert(
        "tools".to_string(),
        serde_yaml_ng::Value::Sequence(yaml_tools),
    );
}

/// Generate Gemini CLI subagent files in `.gemini/agents/<name>.md`.
/// Gemini format: name, description, kind (local), tools, model in YAML frontmatter.
pub fn generate_gemini_agents(
    project_root: &Path,
    agents: &[NormalizedAgent],
) -> Result<Vec<(PathBuf, String)>> {
    let agents_dir = project_root.join(".gemini").join("agents");
    let mut files = Vec::new();

    for agent in agents {
        let filename = format!("{}.md", sanitize_name(&agent.name));
        let mut fields = BTreeMap::new();
        fields.insert(
            "name".to_string(),
            serde_yaml_ng::Value::String(sanitize_name(&agent.name)),
        );
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&agent.description, &agent.name)),
        );
        fields.insert(
            "kind".to_string(),
            serde_yaml_ng::Value::String("local".to_string()),
        );
        insert_tool_list(&mut fields, &gemini_tools(&agent.tools));
        if let Some(model) = gemini_model(agent.model.as_deref()) {
            fields.insert(
                "model".to_string(),
                serde_yaml_ng::Value::String(model.to_string()),
            );
        }

        let content = frontmatter::serialize(&fields, &format!("{}\n", agent.content))?;
        files.push((agents_dir.join(filename), content));
    }

    Ok(files)
}

/// Generate Kiro skill files in `.kiro/skills/<name>/SKILL.md`.
pub fn generate_kiro_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".kiro").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate Devin skill files in `<skills_dir>/<name>/SKILL.md`
/// (`.devin/skills/`). Devin documents no `disable-model-invocation`; a
/// manual-only skill is `triggers: [user]` instead (the default is
/// `[user, model]`). `allowed-tools` only pre-approves Devin's own tool names
/// (`read`, `edit`, `exec`, …) and restricts nothing, so it is not copied.
pub fn generate_devin_skills(
    skills_dir: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );

        if skill.manual_invocation {
            fields.insert(
                "triggers".to_string(),
                serde_yaml_ng::Value::Sequence(vec!["user".into()]),
            );
        }
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate Zoo Code skill files in `.roo/skills/<name>/SKILL.md`.
/// Zoo Code skills use `name` and `description` in frontmatter.
pub fn generate_zoocode_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".roo").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate OpenCode skill files in `.opencode/skills/<name>/SKILL.md`.
/// OpenCode skills recognize only `name`, `description`, `license`, `compatibility`,
/// and `metadata`. `allowed-tools` is not a recognized field.
pub fn generate_opencode_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".opencode").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate OpenCode subagent markdown files in `.opencode/agents/<name>.md`.
/// OpenCode reads per-project agent markdown files from `.opencode/agents/`.
pub fn generate_opencode_agents_md(
    project_root: &Path,
    agents: &[NormalizedAgent],
) -> Result<Vec<(PathBuf, String)>> {
    let agents_dir = project_root.join(".opencode").join("agents");
    let mut files = Vec::new();

    for agent in agents {
        let filename = format!("{}.md", sanitize_name(&agent.name));
        let mut fields = BTreeMap::new();
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&agent.description, &agent.name)),
        );
        fields.insert(
            "mode".to_string(),
            serde_yaml_ng::Value::String("subagent".to_string()),
        );
        if let Some(model) = opencode_model(agent.model.as_deref()) {
            fields.insert(
                "model".to_string(),
                serde_yaml_ng::Value::String(model.to_string()),
            );
        }

        let content = frontmatter::serialize(&fields, &format!("{}\n", agent.content))?;
        files.push((agents_dir.join(filename), content));
    }

    Ok(files)
}

/// The `model` to write for an OpenCode agent. OpenCode resolves it as
/// `provider/model`, so a bare id such as `gpt-4o` or `sonnet` would become
/// provider `gpt-4o` with an empty model; such values are left out and the
/// agent uses OpenCode's default model.
pub(crate) fn opencode_model(model: Option<&str>) -> Option<&str> {
    model.filter(|m| {
        m.split_once('/')
            .is_some_and(|(provider, id)| !provider.is_empty() && !id.is_empty())
    })
}

/// The `model` to write for a Claude Code subagent: an alias (`sonnet`,
/// `opus`, `haiku`, `fable`), `inherit`, or a full `claude-*` id. Another
/// vendor's id (`gpt-4o`, `gemini-2.5-pro`) is left out, and the subagent
/// uses Claude Code's default model order. So is a dotted id such as Kiro's
/// `claude-sonnet-4.5`: Claude Code spells versions with hyphens.
pub(crate) fn claude_model(model: Option<&str>) -> Option<&str> {
    model.filter(|m| {
        matches!(*m, "sonnet" | "opus" | "haiku" | "fable" | "inherit")
            || (m.starts_with("claude-") && !m.contains('.'))
    })
}

/// A model value that only means something to another host: a Claude Code or
/// Gemini CLI alias, or an OpenCode `provider/model` id.
fn is_foreign_model_alias(model: &str) -> bool {
    matches!(
        model,
        "sonnet" | "opus" | "haiku" | "fable" | "pro" | "flash" | "flash-lite"
    ) || model.contains('/')
}

/// The `model` to write for a Kiro agent. Kiro CLI V3 keeps an unknown model
/// selected and fails every request, so another host's alias and `inherit`
/// (not a Kiro value) are left out and the agent uses Kiro's default.
pub(crate) fn kiro_model(model: Option<&str>) -> Option<&str> {
    model.filter(|m| *m != "inherit" && !is_foreign_model_alias(m))
}

/// The `model` to write for a Copilot custom agent (a model name or id such
/// as `GPT-5 (copilot)` or `gpt-4o`); another host's alias is left out.
pub(crate) fn copilot_model(model: Option<&str>) -> Option<&str> {
    model.filter(|m| *m != "inherit" && !is_foreign_model_alias(m))
}

/// The `model` to write for a Cursor subagent: `inherit` or a model id;
/// another host's alias is left out.
pub(crate) fn cursor_model(model: Option<&str>) -> Option<&str> {
    model.filter(|m| !is_foreign_model_alias(m))
}

/// The `model` to write for a Gemini CLI subagent. Gemini passes any other
/// value to its API unchanged, so a Claude alias such as `sonnet` would load
/// and then fail on every call; only `inherit`, Gemini's aliases (`auto`,
/// `pro`, `flash`, `flash-lite`), `gemini-*` ids and the `gemma-*` ids
/// Gemini CLI also accepts are written.
pub(crate) fn gemini_model(model: Option<&str>) -> Option<&str> {
    model.filter(|m| {
        matches!(*m, "inherit" | "auto" | "pro" | "flash" | "flash-lite")
            || m.starts_with("gemini-")
            || m.starts_with("gemma-")
    })
}

/// Generate DeepSeek Harness skill files in `.dsh/skills/<name>/SKILL.md`.
/// The harness filesystem skill provider scans `<projectRoot>/.dsh/skills` first
/// and interprets required `name` and `description`, plus optional `whenToUse`,
/// `metadata`, `disable-model-invocation` and `user-invocable`. `allowed-tools`
/// is not a recognized field, and names must be kebab-case.
pub fn generate_deepseek_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".dsh").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

/// Generate Gemini CLI skill files in `.gemini/skills/<name>/SKILL.md`.
/// Gemini skills use ONLY `name` and `description` (no other fields allowed).
pub fn generate_gemini_skills(
    project_root: &Path,
    skills: &[NormalizedSkill],
) -> Result<Vec<(PathBuf, String)>> {
    let skills_dir = project_root.join(".gemini").join("skills");
    let mut files = Vec::new();

    for skill in skills {
        let skill_name = sanitize_name(&skill.name);
        let skill_dir = skills_dir.join(&skill_name);
        let skill_path = skill_dir.join("SKILL.md");

        let mut fields = BTreeMap::new();
        fields.insert("name".to_string(), serde_yaml_ng::Value::String(skill_name));
        fields.insert(
            "description".to_string(),
            serde_yaml_ng::Value::String(description_or_name(&skill.description, &skill.name)),
        );
        // Gemini docs: "do not include any other fields" — no allowed-tools

        add_invocation_fields(&mut fields, skill);
        let content = frontmatter::serialize(&fields, &format!("{}\n", skill.content))?;
        files.push((skill_path, content));
        files.extend(bundled_outputs(&skill_dir, skill));
        if let Some(policy) = invocation_policy(&skill_dir, skill, false)? {
            files.push(policy);
        }
    }

    Ok(files)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty_description_falls_back_to_name_for_every_host() {
        // Codex, Copilot, Gemini, OpenCode and Zoo Code skip a skill or agent
        // without a description, so none may be written without one.
        let root = Path::new("/tmp/test");
        let skills = vec![NormalizedSkill {
            name: "deploy".to_string(),
            content: "Run deploy.".to_string(),
            ..Default::default()
        }];
        let agents = vec![NormalizedAgent {
            name: "reviewer".to_string(),
            content: "Review.".to_string(),
            ..Default::default()
        }];
        let skill_files = [
            generate_claude_skills(root, &skills).unwrap(),
            generate_cursor_skills(root, &skills).unwrap(),
            generate_codex_skills(root, &skills).unwrap(),
            generate_copilot_skills(root, &skills).unwrap(),
            generate_kiro_skills(root, &skills).unwrap(),
            generate_devin_skills(&root.join(".devin/skills"), &skills).unwrap(),
            generate_zoocode_skills(root, &skills).unwrap(),
            generate_opencode_skills(root, &skills).unwrap(),
            generate_deepseek_skills(root, &skills).unwrap(),
            generate_gemini_skills(root, &skills).unwrap(),
        ];
        for files in skill_files {
            assert!(
                files[0].1.contains("description: deploy\n"),
                "{}",
                files[0].1
            );
        }
        let agent_files = [
            generate_claude_agents(root, &agents).unwrap(),
            generate_cursor_agents(root, &agents).unwrap(),
            generate_copilot_agents(root, &agents).unwrap(),
            generate_kiro_agents(root, &agents).unwrap(),
            generate_gemini_agents(root, &agents).unwrap(),
            generate_opencode_agents_md(root, &agents).unwrap(),
        ];
        for files in agent_files {
            assert!(
                files[0].1.contains("description: reviewer\n"),
                "{}",
                files[0].1
            );
        }
    }

    #[test]
    fn test_cursor_agent_name_is_sanitized() {
        // Cursor subagent names use lowercase letters and hyphens.
        let agents = vec![NormalizedAgent {
            name: "Code Reviewer".to_string(),
            description: "Review".to_string(),
            ..Default::default()
        }];
        let files = generate_cursor_agents(Path::new("/tmp/test"), &agents).unwrap();
        assert!(
            files[0].1.contains("name: code-reviewer\n"),
            "{}",
            files[0].1
        );
    }

    #[test]
    fn test_generate_claude_skill() {
        let skills = vec![NormalizedSkill {
            name: "deploy".to_string(),
            description: "Deploy the app".to_string(),
            content: "Run npm run deploy".to_string(),
            allowed_tools: vec!["Bash".to_string()],
            ..Default::default()
        }];
        let files = generate_claude_skills(Path::new("/tmp/test"), &skills).unwrap();
        assert_eq!(files.len(), 2); // SKILL.md + conforme marker
        assert!(files[0].0.to_string_lossy().ends_with("SKILL.md"));
        assert!(files[0].1.contains("name: deploy"));
        assert!(files[0].1.contains("description: Deploy the app"));
        assert!(files[0].1.contains("allowed-tools: Bash"));
    }

    #[test]
    fn test_generate_copilot_skill() {
        // Copilot documents skills at `.github/skills/<name>/SKILL.md`.
        let skills = vec![NormalizedSkill {
            name: "Deploy App".to_string(),
            description: "Deploy the app".to_string(),
            content: "Run npm run deploy".to_string(),
            allowed_tools: vec!["shell".to_string(), "bash".to_string()],
            ..Default::default()
        }];
        let files = generate_copilot_skills(Path::new("/tmp/test"), &skills).unwrap();
        assert_eq!(files.len(), 2); // SKILL.md + conforme marker
        assert!(files[0]
            .0
            .to_string_lossy()
            .ends_with(".github/skills/deploy-app/SKILL.md"));
        assert!(files[0].1.contains("name: deploy-app"));
        assert!(files[0].1.contains("description: Deploy the app"));
        assert!(files[0].1.contains("allowed-tools: shell bash"));
        assert!(files[0].1.contains("Run npm run deploy"));
    }

    #[test]
    fn test_generate_copilot_agent() {
        let agents = vec![crate::config::NormalizedAgent {
            name: "reviewer".to_string(),
            description: "Code reviewer".to_string(),
            content: "Review for bugs.".to_string(),
            model: Some("gpt-4o".to_string()),
            tools: vec!["codebase".to_string()],
            ..Default::default()
        }];
        let files = generate_copilot_agents(Path::new("/tmp/test"), &agents).unwrap();
        assert_eq!(files.len(), 1);
        assert!(files[0].0.to_string_lossy().ends_with(".agent.md"));
        assert!(files[0].1.contains("name: reviewer"));
        assert!(files[0].1.contains("model: gpt-4o"));
    }

    #[test]
    fn test_foreign_model_aliases_are_left_out() {
        // A Claude alias or an OpenCode `provider/model` id means nothing to
        // Kiro (whose V3 requests then fail), Copilot or Cursor.
        for m in ["sonnet", "opus", "flash", "anthropic/claude-sonnet-4-5"] {
            assert_eq!(kiro_model(Some(m)), None, "{m}");
            assert_eq!(copilot_model(Some(m)), None, "{m}");
            assert_eq!(cursor_model(Some(m)), None, "{m}");
        }
        assert_eq!(kiro_model(Some("inherit")), None);
        assert_eq!(cursor_model(Some("inherit")), Some("inherit"));
        assert_eq!(kiro_model(Some("auto")), Some("auto"));
        assert_eq!(
            kiro_model(Some("claude-sonnet-4.5")),
            Some("claude-sonnet-4.5")
        );
        assert_eq!(
            copilot_model(Some("GPT-5 (copilot)")),
            Some("GPT-5 (copilot)")
        );
        assert_eq!(copilot_model(Some("gpt-4o")), Some("gpt-4o"));
        assert_eq!(gemini_model(Some("gemma-4-27b-it")), Some("gemma-4-27b-it"));
        assert_eq!(claude_model(Some("claude-sonnet-4.5")), None);
        assert_eq!(
            claude_model(Some("claude-sonnet-4-5")),
            Some("claude-sonnet-4-5")
        );
        assert_eq!(gemini_model(Some("sonnet")), None);
    }

    #[test]
    fn test_agent_model_is_filtered_for_kiro_copilot_and_cursor() {
        let agents = vec![crate::config::NormalizedAgent {
            name: "reviewer".to_string(),
            description: "Review".to_string(),
            content: "Review.".to_string(),
            model: Some("sonnet".to_string()),
            ..Default::default()
        }];
        let root = Path::new("/tmp/test");
        for files in [
            generate_kiro_agents(root, &agents).unwrap(),
            generate_copilot_agents(root, &agents).unwrap(),
            generate_cursor_agents(root, &agents).unwrap(),
        ] {
            assert!(!files[0].1.contains("model:"), "{}", files[0].1);
        }
    }

    #[test]
    fn test_mcp_wildcard_translates_between_gemini_and_kiro() {
        assert_eq!(gemini_tools(&["mcp_*".to_string()]), vec!["mcp_*"]);
        assert_eq!(gemini_tools(&["@mcp".to_string()]), vec!["mcp_*"]);
        assert_eq!(kiro_tools(&["mcp_*".to_string()]), vec!["@mcp"]);
    }

    #[test]
    fn test_kiro_todo_tool_is_todo() {
        assert_eq!(kiro_tools(&["TodoWrite".to_string()]), vec!["todo"]);
        assert_eq!(kiro_tools(&["write_todos".to_string()]), vec!["todo"]);
    }

    #[test]
    fn test_current_claude_code_tools_pass_through() {
        let tools: Vec<String> = [
            "Read",
            "Workflow",
            "ListAgents",
            "ScheduleWakeup",
            "SendUserFile",
        ]
        .iter()
        .map(|t| t.to_string())
        .collect();
        assert_eq!(claude_tools(&tools), tools);
    }

    #[test]
    fn test_bundled_files_skip_metadata_and_nested_skills() {
        let dir = tempfile::tempdir().unwrap();
        let skill = dir.path().join("deploy");
        std::fs::create_dir_all(skill.join("scripts")).unwrap();
        std::fs::create_dir_all(skill.join("agents")).unwrap();
        std::fs::create_dir_all(skill.join("nested")).unwrap();
        std::fs::write(skill.join("SKILL.md"), "---\nname: deploy\n---\nRun.\n").unwrap();
        std::fs::write(skill.join("scripts/run.sh"), "echo\n").unwrap();
        std::fs::write(skill.join("agents/openai.yaml"), "policy: {}\n").unwrap();
        std::fs::write(skill.join(".DS_Store"), "x").unwrap();
        std::fs::write(
            skill.join("nested/SKILL.md"),
            "---\nname: nested\n---\nN.\n",
        )
        .unwrap();
        std::fs::write(skill.join("logo.png"), [0xffu8, 0xfe, 0x00]).unwrap();

        let files = read_bundled_files(&skill).unwrap();

        assert_eq!(files.keys().collect::<Vec<_>>(), vec!["scripts/run.sh"]);
        assert_eq!(
            uncarried_skill_files(&skill).unwrap(),
            vec![skill.join("logo.png")]
        );
    }
}
